spring.application.name=rate-limiter
server.port=8080
#toggle flag to turn the service on/off
server.servlet.contextPath=/rate-limiter
rate-limiter.enabled=${RATE_LIMITER_ENABLED:true}
#Maximum 100 requests allowed in a window
rate-limiter.max-requests=${RATE_LIMITER_MAX_REQUESTS:10}
rate-limiter.window-seconds=${RATE_LIMITER_WINDOW_SECONDS:60}
rate-limiter.strategy=${RATE_LIMITER_STRATEGY:fixed-window}

#Leaky-Bucket
rate-limiter.leaky-capacity=${RATE_LIMITER_LEAKY_CAPACITY:5}
rate-limiter.leaky-rate=${RATE_LIMITER_LEAKY_RATE:1}
