spring.application.name=rate-limiter
server.port=8080
#toggle flag to turn the service on/off
server.servlet.contextPath=/rate-limiter
rate-limiter.enabled=true
#Maximum 100 requests allowed in a window
rate-limiter.max-requests=10
rate-limiter.window-seconds=60
rate-limiter.strategy=token-bucket

#Leaky-Bucket
rate-limiter.leaky-capacity=5
rate-limiter.leaky-rate=1
